version: '2.4'

services:
  manage-case-assignment:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/aac/manage-case-assignment:latest
    environment:
      IDAM_URL: https://idam-web-public.aat.platform.hmcts.net
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      MANAGE_CASE_S2S_KEY: "AAAAAAAAAAAAAAAA" # use aat key from vault
      MANAGE_CASE_S2S_AUTHORISED_SERVICES: ccd_gw,xui_webapp,ccd_data
      CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal
      CCD_DEFINITION_STORE_API_BASE_URL: http://ccd-definition-store-api-aat.service.core-compute-aat.internal
      PRD_HOST: http://rd-professional-api-aat.service.core-compute-aat.internal
      NOTIFY_MCA_API_KEY: "notify-test-api-key"
      # for debug JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - $SERVER_PORT:$SERVER_PORT
