---
version: '2.4'

services:
  manage-case-assignment:
    image: "hmctspublic.azurecr.io/aac/manage-case-assignment:${MANAGE_CASE_ASSIGNMENT_TAG:-latest}"
    container_name: manage-case-assignment
    environment:
      SERVER_PORT: 4454
      IDAM_API_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_OIDC_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      S2S_URL: http://service-auth-provider-api:8080
      MANAGE_CASE_S2S_KEY: "AAAAAAAAAAAAAAAA"
      MANAGE_CASE_S2S_AUTHORISED_SERVICES: xui_webapp,ccd_data
      CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api:4452
      CCD_DEFINITION_STORE_API_BASE_URL: http://ccd-definition-store-api:4451
      ROLE_ASSIGNMENT_URL: "${ROLE_ASSIGNMENT_URL:-http://am-role-assignment-service:4096}"
      PRD_HOST: http://aca-wiremock:8080
      NOTIFY_MCA_API_KEY: "notify-test-api-key"
      MCA_CONDITIONAL_APIS_ORGS_ASSIGNED_USERS_ENABLED: true
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      # JAVA_TOOL_OPTIONS: '-XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
    ports:
      - 4454:4454
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      # - 5005:5005
    depends_on:
      - aca-wiremock
    networks:
      - ccd-network

  aca-wiremock:
    container_name: aca-wiremock
    image: rodolpheche/wiremock
    volumes:
      - ./../mocks/wiremock:/home/wiremock:rw
    ports:
      - 5544:8080
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
